Javascript Ex 1
luciapuccini/startup pull request #3
Opened 2018-05-16 05:09 UTC by luciapuccini

2018-05-16 18:56 UTC, troyax requested changes

2018-05-16 18:56 UTC, troianoandres commented on 01-JS-DOM-APIs/resources/css/style.css
> +#slideSource {
selectors should be writting in other way as we reviewed in the topic 0. For this case it should be `#slide-source`

2018-05-16 18:56 UTC, troianoandres commented on 01-JS-DOM-APIs/resources/js/main.js
> +   function fGetText()
All this function should not be tabbed

2018-05-16 18:56 UTC, troianoandres commented on 01-JS-DOM-APIs/resources/js/main.js
> +  ('click', fGetText);
I'd rather write this in line 21 too

2018-05-17 17:57 UTC, troyax approved these changes

2018-05-17 18:26 UTC, luciapuccini commented
End Topic 1 JS

2018-05-17 18:26 UTC, merged